apiVersion: component.ber.sh/v1beta1
kind: helm

spec:
  source: ./lib/charts/strapi
  image: xxx
  ingressAnnotations:
    alb.ingress.kubernetes.io/group.name: "${CLUSTER_NAME}-public"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: "${CLUSTER_AWS_ACM_ARN}"
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/tags: Environment=xxx,Team=infra
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=60
    alb.ingress.kubernetes.io/shield-advanced-protection: "true"
    alb.ingress.kubernetes.io/load-balancer-attributes: "deletion_protection.enabled=false,access_logs.s3.enabled=false"
    external-dns.alpha.kubernetes.io/hostname: strapi.xxx.com.
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
  resources:
    limits:
      cpu: 400m
      memory: 4Gi
    requests:
      cpu: 200m
      memory: 2Gi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 85
