---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app strapi
  namespace: strapi
spec:
  interval: 30m
  chart:
    spec:
      chart: strapi
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: strapi
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    replicaCount: 1
    image:
      repository: 3333.dkr.ecr.eu-west-1.amazonaws.com/strapi
      pullPolicy: IfNotPresent
      tag: "1.50.8196.31705"
    envFrom:
      - configMapRef:
          name: strapi
      - secretRef:
          name: strapi
    nameOverride: ""
    fullnameOverride: ""
    serviceAccount:
      create: false
      annotations: {}
      name: ""
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}
    service:
      type: ClusterIP
      port: 1337
    ingress:
      enabled: false
    resources: {}
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 4
      targetCPUUtilizationPercentage: 70
    nodeSelector: {}
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: services
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: nodegroup
                  operator: In
                  values:
                    - "services"
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - "strapi"
              topologyKey: topology.kubernetes.io/zone
