---
apiVersion: v1
kind: ConfigMap
metadata:
  name: strapi
  namespace: strapi
data:
  NODE_ENV: production
  AWS_BUCKET: mws-strapi
  DATABASE_HOST: "{{ rds.endpoint }}"
  DATABASE_USERNAME: "{{ rds.user }}"
  DATABASE_NAME: strapi
  DATABASE_PORT: 5432
  DATABASE_CLIENT: postgres
