apiVersion: stack.berbyte.sh/v1beta1
kind: app

spec:
  strapi:
    component: strapi
    cluster: "{{ eks.cluster_name }}"
    stack: dev-euw1
    namespace: strapi

    replicas: 4

    env:
      - name: ENVIRONMENT
        value: dev

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

    autoscaler:
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80

    readinessProbe:
      httpGet: /healthz
